apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todoapp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-server
  template:
    metadata:
      labels:
        app: todoapp-server
    spec:
      containers:
      - name: todoapp-server-container
        image: halitemen123/todoapp-server:latest
        env:
        - name: MONGO_URI
          value: 
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 30000