version: "3"
services:
  todo-app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MONGO_URI: mongodb://mongo
    ports:
      - 16500:16500
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: mydb
    ports:
     - 27017:27017
    volumes:
     - mongo-volume:/data/db
volumes:
  mongo-volume: